[db]
user = "postgres"
password = "12345"
dbname = "eth_archive_db"
host = "localhost"
port = 5432

[data]
query_chunk_size = 256
query_time_limit_ms = 6000

[http_server]
ip = "127.0.0.1"
port = 8080
