block_window_size = 300000

[db]
user = "postgres"
password = "12345"
dbname = "eth_archive_db"
host = "localhost"
port = 5432

[ingest]
eth_rpc_url = "http://195.201.56.33:8545"
block_batch_size = 50
http_req_concurrency = 100
