[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_LOG = "info"

[tasks.ingester]
workspace = false
command = "cargo"
args = [
	"run", "--release","--bin", "eth-archive-ingester", "--",
	"--data-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "50",
	"--http-req-concurrency", "100",
	"--max-blocks-per-file", "100000",
	"--max-txs-per-file", "200000",
	"--max-logs-per-file", "200000",
]

[tasks.worker]
workspace = false
command = "cargo"
args = [
	"run", "--release", "--bin", "eth-archive-worker", "--",
	"--db-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/db",
	"--data-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "50",
	"--http-req-concurrency", "100",
	"--min-hot-block-range", "100500",
	"--max-resp-body-size", "30",
	"--resp-time-limit", "5000",
]

[tasks.sync-s3]
workspace = false
command = "mc"
args = [
	"mirror", "--watch",
	"${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data",
	"subsquid-filebase/eth0",
	"--exclude", "*temp/*",
]
