[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_LOG = "info,aws_config=off"

[tasks.ingester]
workspace = false
command = "cargo"
args = [
	"run", "--release","--bin", "eth-archive-ingester", "--",
	"--data-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data/parquet",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "10",
	"--http-req-concurrency", "200",
	"--default-rpc-url", "https://rpc.ankr.com/eth",
	"--max-blocks-per-file", "100000",
	"--max-txs-per-file", "100000",
	"--max-logs-per-file", "100000",
	"--max-row-groups-per-file", "16",
]

[tasks.worker]
workspace = false
command = "cargo"
args = [
	"run", "--release", "--bin", "eth-archive-worker", "--",
	"--db-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data/db",
	"--data-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data/parquet",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "10",
	"--http-req-concurrency", "200",
	"--default-rpc-url", "https://rpc.ankr.com/eth",
	"--initial-hot-block-range", "10000",
	"--max-resp-body-size", "30",
	"--resp-time-limit", "5000",
]

[tasks.ingester-s3]
workspace = false
command = "cargo"
args = [
	"run", "--release","--bin", "eth-archive-ingester", "--",
	"--data-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data/s3/ingester",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "10",
	"--http-req-concurrency", "200",
	"--default-rpc-url", "https://rpc.ankr.com/eth",
	"--max-blocks-per-file", "100000",
	"--max-txs-per-file", "100000",
	"--max-logs-per-file", "100000",
	"--max-row-groups-per-file", "16",
	"--s3-endpoint", "https://s3.filebase.com",
	"--s3-bucket-name", "eth0",
	"--s3-bucket-region", "us-east-1",
	"--s3-sync-interval-secs", "10",
	"--s3-concurrency", "32",
]

[tasks.worker-s3]
workspace = false
command = "cargo"
args = [
	"run", "--release", "--bin", "eth-archive-worker", "--",
	"--db-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data/s3/worker/db",
	"--data-path", "${CARGO_MAKE_WORKSPACE_WORKING_DIRECTORY}/data/s3/worker/parquet",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "10",
	"--http-req-concurrency", "200",
	"--default-rpc-url", "https://rpc.ankr.com/eth",
	"--max-resp-body-size", "30",
	"--resp-time-limit", "5000",
	"--s3-endpoint", "https://s3.filebase.com",
	"--s3-bucket-name", "eth-archive-stage-1-sia",
	"--s3-bucket-region", "us-east-1",
	"--s3-sync-interval-secs", "10",
	"--s3-concurrency", "32",
]
