[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
RUST_LOG = "info"

[tasks.ingester]
workspace = false
command = "cargo"
args = [
	"run", "--release","--bin", "eth-archive-ingester", "--",
	"--data-path", "./data",
	"--eth-rpc-url", "http://195.201.56.33:8545",
	"--request-timeout-secs", "300",
	"--connect-timeout-ms", "1000",
	"--block-batch-size", "50",
	"--http-req-concurrency", "100",
	"--best-block-offset", "10",
	"--max-blocks-per-file", "100000",
	"--max-txs-per-file", "200000",
	"--max-logs-per-file", "150000",
]

[tasks.gateway]
workspace = false
command = "cargo"
args = [
	"run", "--release", "--bin", "eth-archive-gateway", "--",
	"--data-path", "./data",
	"--max-block-range", "500000",
	"--default-block-range", "1000000",
	"--response-log-limit", "10000",
	"--query-chunk-size", "256",
	"--query-time-limit-ms", "6000",
]
