[package]
name = "eth-archive-ingester"
version = "0.0.1"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1.0"
log = "0.4"
env_logger = "0.9"
clap = { version = "4", features = ["derive"] }

eth-archive-core = { path = "../core" }

[dependencies.arrow2]
version = "0.14"
features = [ "io_parquet", "io_parquet_compression", "compute" ]
