[package]
name = "eth-archive-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
bytes = "1"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
log = "0.4.17"
env_logger = "0.9"
clap = { version = "4", features = ["derive"] }
prefix-hex = "0.4"
rayon = "1"
itertools = "0.10"
actix-web = "4"
solana-bloom = "1"
rmp-serde = "1.1.1"

eth-archive-core = { path = "../core" }

[dependencies.polars]
version = "0.25"
features = [ "performant", "lazy", "is_in", "dtype-full", "parquet", "cse" ]

[dependencies.rocksdb]
version = "0.19"
default-features = false
features = ["lz4"]
