CREATE TABLE eth_block (
    row_id BIGSERIAL PRIMARY KEY,
    number bigint,
    hash blob,
    parent_hash blob,
    nonce blob,
    sha3_uncles blob,
    logs_bloom blob,
    transactions_root blob,
    state_root blob,
    receipts_root blob,
    miner blob,
    difficulty blob,
    total_difficulty blob,
    extra_data blob,
    size bigint,
    gas_limit blob,
    gas_used blob,
    timestamp bigint,
    uncles blob
);

CREATE TABLE IF NOT EXISTS eth_tx (
    row_id BIGSERIAL PRIMARY KEY,
    hash bytea,
    nonce bytea,
    block_hash bytea,
    block_number bigint,
    transaction_index bytea,
    sender bytea,
    receiver bytea,
    value bytea,
    gas_price bytea,
    gas bytea,
    input bytea,
    v bytea,
    standard_v boolean,
    r bytea,
    raw bytea,
    public_key bytea,
    chain_id bytea,
    block_row_id BIGINT NOT NULL REFERENCES eth_block(row_id),
);

CREATE TABLE IF NOT EXISTS eth_log (
    row_id BIGSERIAL PRIMARY KEY,
    removed boolean,
    log_index blob,
    transaction_index blob,
    transaction_hash blob,
    block_hash blob,
    block_number bigint,
    address blob,
    data blob,
    topic0 blob,
    topic1 blob,
    topic2 blob,
    topic3 blob,
    block_row_id BIGINT NOT NULL REFERENCES eth_block(row_id),
);
