CREATE TABLE eth_block (
    row_id BIGSERIAL PRIMARY KEY,
    number bigint,
    hash bytea,
    parent_hash bytea,
    nonce bytea,
    sha3_uncles bytea,
    logs_bloom bytea,
    transactions_root bytea,
    state_root bytea,
    receipts_root bytea,
    miner bytea,
    difficulty bytea,
    total_difficulty bytea,
    extra_data bytea,
    size bigint,
    gas_limit bytea,
    gas_used bytea,
    timestamp bigint,
    uncles bytea
);

CREATE TABLE eth_tx (
    row_id BIGSERIAL PRIMARY KEY,
    hash bytea,
    nonce bytea,
    block_hash bytea,
    block_number bigint,
    transaction_index bytea,
    sender bytea,
    receiver bytea,
    value bytea,
    gas_price bytea,
    gas bytea,
    input bytea,
    v bytea,
    standard_v boolean,
    r bytea,
    raw bytea,
    public_key bytea,
    chain_id bytea,
    block_row_id BIGINT NOT NULL REFERENCES eth_block(row_id)
);

CREATE TABLE eth_log (
    row_id BIGSERIAL PRIMARY KEY,
    removed boolean,
    log_index bytea,
    transaction_index bytea,
    transaction_hash bytea,
    block_hash bytea,
    block_number bigint,
    address bytea,
    data bytea,
    topic0 bytea,
    topic1 bytea,
    topic2 bytea,
    topic3 bytea,
    block_row_id BIGINT NOT NULL REFERENCES eth_block(row_id)
);
